### ISSUE TITLE
"listen 6000" is deprecated

### ISSUE THREAD

**Issue by laukstein** [RemoteDebug/remotedebug-firefox-adapter#9]
README.md needs to be updated.
`listen 6000` is deprecated, instead use `--start-debugger-server` (`-start-debugger-server` on Win).

>    https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop
>    Firefox 37 onwards

>    From Firefox 37 onwards the above method still works, but there's an alternative: run the debuggee from the command line, passing it the --start-debugger-server option:
>    `/path/to/firefox --start-debugger-server`

>    Passed with no arguments, --start-debugger-server makes the debugger server listen on port 6000. To use a different port, pass the desired port number:
>    `/path/to/firefox --start-debugger-server 1234`

>    Note: in Windows, the start-debugger-server call will only have one dash:
>    `firefox.exe -start-debugger-server 1234`

**Comment by auchenberg** [comment]
Great news! Do you mind submitting a PR?

**Comment by laukstein** [comment]
PR? What do you mean?

**Comment by auchenberg** [comment]
I meant a Pull Request with the updated instructions.

Readme updated in https://github.com/RemoteDebug/remotedebug-firefox-adapter/commit/872f90b9928cc9b2f66ebcfc9d76d76aa81a0f08

**Comment by laukstein** [comment]
Ok. I just remove `6000` since no need to mention it till used another port, https://github.com/RemoteDebug/remotedebug-firefox-adapter/pull/10.
